"""
Probe B v2 — Re-optimize production stack weights on the 1416-row
broader-pool intersection (96% of the 1478 substrate).

The 1478 substrate is files-with-labels rows (66 files, variable rows
per file). B1 PerceiverIO and ProtoSSM v4 in d2_beta_oofs.npz cover only
the 59 files with the fixed-12-window cache (= 708 windows). 7 files
(0006, 0007, 0008, 0009, 0010, 0015, 0026) are not in the local Perch
cache, so 62 of the 1478 rows cannot get B1/Proto predictions.

Strategy:
    For the 1416-row intersection (96% coverage):
        - A1: take v4 5-fold OOF predictions (5-fold rank-mean,
              matches production cell 41).
        - B1: take d2_beta_oofs B1 predictions, BROADCAST from
              708 → 1416 via (file, start_sec) join. Each cache
              row maps to exactly 2 v4 rows (label duplicates).
        - Proto: same broadcast.
        - y_true: take v4's 1478-substrate y_true (subset to 1416).
    Then sweep linear rank-fusion weights and score with broader-pool
    macro AUC over active classes.

This is more credible than the pure 708-substrate sweep (used in
probe_b_weight_sweep.py) because:
    1. Y is from the labels CSV at 1416/1478 ≈ 96% coverage.
    2. A1 is 5-fold (production), not 4-fold (d2_beta).
    3. Broader-pool methodology with real label rows.

Caveats:
    - B1 OOF was generated by 5-fold GroupKFold over 59 files in d2_beta;
      a true 66-file 5-fold would give different fold assignments. The
      7 missing files' contribution to broader-pool AUC is dropped.
    - B1's standalone broader-pool AUC is 0.40 on the 708 substrate
      (anti-predictive at the macro level — see probe_b_weight_sweep.py
      results) and may stay ~0.4-0.5 here. Treat the sweep as
      diagnostic, not authoritative.
"""
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from pathlib import Path

OUT_PATH = Path("/home/swatson/work/kaggle/BirdCLEF/four_track/data/probe_b_weight_sweep.npz")


def macro_auc_skip_empty(y, p):
    aucs = []
    for c in range(y.shape[1]):
        yc = y[:, c]
        if yc.sum() == 0 or yc.sum() == len(yc):
            continue
        try:
            aucs.append(roc_auc_score(yc, p[:, c]))
        except Exception:
            pass
    return float(np.mean(aucs)), len(aucs)


def rank01_per_col(mat):
    n = mat.shape[0]
    order = np.argsort(mat, axis=0, kind="mergesort")
    ranks = np.empty_like(order, dtype=np.float32)
    rows = np.arange(n, dtype=np.float32)
    for c in range(mat.shape[1]):
        ranks[order[:, c], c] = rows
    if n > 1:
        ranks /= (n - 1)
    return ranks


def main():
    # --- Build 708 → 1478 join map ---
    m = pd.read_parquet(
        "/home/swatson/work/kaggle/BirdCLEF/data/processed/perch_cache/full_perch_meta.parquet"
    )
    m["start_sec"] = m["row_id"].str.rsplit("_", n=1).str[-1].astype(int) - 5
    m["cache_idx"] = np.arange(len(m))

    v4 = np.load(
        "/home/swatson/work/kaggle/BirdCLEF/four_track/data/v4_5fold_soundscape_oof.npz",
        allow_pickle=True,
    )
    v4_df = pd.DataFrame(
        {"filename": v4["filenames"], "start_sec": v4["start_sec"].astype(int)}
    )
    v4_df["v4_idx"] = np.arange(len(v4_df))

    joined = m.merge(v4_df, on=["filename", "start_sec"], how="inner")
    print(f"708 cache ↔ 1478 substrate: {len(joined)} rows ({len(joined)/1478:.1%} coverage)", flush=True)
    print(f"7 files dropped: {1478 - len(joined)} rows uncovered", flush=True)

    cache_idx = joined["cache_idx"].to_numpy()
    v4_idx = joined["v4_idx"].to_numpy()

    # --- Load components ---
    d_beta = np.load(
        "/home/swatson/work/kaggle/BirdCLEF/four_track/data/d2_beta_oofs.npz",
        allow_pickle=True,
    )
    b1_oof_708 = d_beta["b1_oof"].astype(np.float32)
    proto_oof_708 = d_beta["proto_oof"].astype(np.float32)
    a1_w_prod = float(d_beta["a1_weight_prod"])
    b1_w_prod = float(d_beta["b1_weight_prod"])

    # A1 5-fold: rank-fuse per fold, mean across folds (production formula)
    v4_perfold = v4["probs_per_fold"]  # (5, 1478, 234)
    v4_y = v4["y_true"].astype(np.float32)
    a1_ranks_perfold_full = np.stack(
        [rank01_per_col(v4_perfold[i]) for i in range(5)], axis=0
    )
    a1_ranks_full = a1_ranks_perfold_full.mean(axis=0).astype(np.float32)  # (1478, 234)

    # Project all components to the 1416-row intersection
    a1_r = a1_ranks_full[v4_idx]                     # (1416, 234)
    y = v4_y[v4_idx]                                 # (1416, 234)
    # Broadcast 708 → 1416 via cache_idx mapping
    b1_708_r = rank01_per_col(b1_oof_708)
    proto_708_r = rank01_per_col(proto_oof_708)
    b1_r = b1_708_r[cache_idx]                       # (1416, 234)
    proto_r = proto_708_r[cache_idx]                 # (1416, 234)

    print(f"\nWorking substrate: {y.shape[0]} rows × {y.shape[1]} classes", flush=True)

    # Standalone diagnostics
    auc_a1, n_a = macro_auc_skip_empty(y, a1_r)
    auc_b1, _ = macro_auc_skip_empty(y, b1_r)
    auc_proto, _ = macro_auc_skip_empty(y, proto_r)
    print(f"\nStandalone broader-pool macro AUC (active-class subset, n_active={n_a}):", flush=True)
    print(f"  A1 (5-fold rank-mean) : {auc_a1:.4f}", flush=True)
    print(f"  B1 (rank, 708→1416)   : {auc_b1:.4f}", flush=True)
    print(f"  ProtoSSM (rank, 708→1416): {auc_proto:.4f}", flush=True)

    # Sanity: A1 5-fold rank on 1478 should be 0.7672 per §25.5; on 1416 it should be similar
    auc_a1_full, _ = macro_auc_skip_empty(v4_y, a1_ranks_full)
    print(f"  A1 (5-fold rank-mean) on full 1478: {auc_a1_full:.4f}  (sanity: §25.5 reports 0.7672)", flush=True)

    # Production-weight rank-fused baseline
    proto_w_prod = 1.0 - a1_w_prod - b1_w_prod
    fused_baseline = a1_w_prod * a1_r + b1_w_prod * b1_r + proto_w_prod * proto_r
    auc_baseline, _ = macro_auc_skip_empty(y, fused_baseline)
    print(f"\nProduction-weight rank-fused AUC: {auc_baseline:.4f}", flush=True)
    print(f"  (A1={a1_w_prod:.2f} B1={b1_w_prod:.2f} Proto={proto_w_prod:.2f})", flush=True)

    # ---- Sweep ----
    a1_grid = np.round(np.arange(0.0, 0.51, 0.05), 2)
    b1_grid = np.round(np.arange(0.0, 0.31, 0.05), 2)
    print(f"\nSweep: A1 ∈ {a1_grid.tolist()}", flush=True)
    print(f"       B1 ∈ {b1_grid.tolist()}", flush=True)

    sweep_grid = []
    sweep_aucs = []
    for a1_w in a1_grid:
        for b1_w in b1_grid:
            proto_w = 1.0 - a1_w - b1_w
            if proto_w < -1e-9:
                continue
            fused = a1_w * a1_r + b1_w * b1_r + proto_w * proto_r
            auc, _ = macro_auc_skip_empty(y, fused)
            sweep_grid.append((float(a1_w), float(b1_w), float(proto_w)))
            sweep_aucs.append(float(auc))

    sweep_grid_arr = np.array(sweep_grid, dtype=np.float32)
    sweep_aucs_arr = np.array(sweep_aucs, dtype=np.float32)

    order = np.argsort(-sweep_aucs_arr)
    print(f"\nTop 5 weight combos:", flush=True)
    print(f"{'A1':>6}  {'B1':>6}  {'Proto':>6}  {'AUC':>8}  {'Δ vs baseline':>14}", flush=True)
    for i in order[:5]:
        a, b, p = sweep_grid_arr[i]
        auc = sweep_aucs_arr[i]
        print(f"{a:6.2f}  {b:6.2f}  {p:6.2f}  {auc:8.4f}  {auc - auc_baseline:+14.4f}", flush=True)

    best_idx = int(order[0])
    best_w = sweep_grid_arr[best_idx]
    best_auc = float(sweep_aucs_arr[best_idx])
    delta = best_auc - auc_baseline
    print(f"\nBest:     A1={best_w[0]:.2f} B1={best_w[1]:.2f} Proto={best_w[2]:.2f} → {best_auc:.4f}", flush=True)
    print(f"Baseline: A1={a1_w_prod:.2f} B1={b1_w_prod:.2f} Proto={1-a1_w_prod-b1_w_prod:.2f} → {auc_baseline:.4f}", flush=True)
    print(f"Delta:    {delta:+.4f}   (gate: ≥ +0.005)", flush=True)
    gate_pass = delta >= 0.005
    print(f"Gate:     {'PASS' if gate_pass else 'FAIL'}", flush=True)

    np.savez(
        OUT_PATH,
        best_weights=best_w,
        best_auc=best_auc,
        baseline_auc=auc_baseline,
        sweep_grid=sweep_grid_arr,
        sweep_aucs=sweep_aucs_arr,
        a1_w_prod=a1_w_prod,
        b1_w_prod=b1_w_prod,
        substrate_n_rows=int(y.shape[0]),
        substrate_n_classes=int(y.shape[1]),
        n_active_classes=int(n_a),
        coverage_fraction=float(len(joined) / 1478),
        gate_pass=int(gate_pass),
        gate_threshold=0.005,
        auc_a1_standalone=auc_a1,
        auc_b1_standalone=auc_b1,
        auc_proto_standalone=auc_proto,
        auc_a1_full_1478=auc_a1_full,
        n_uncovered_rows=int(1478 - len(joined)),
    )
    print(f"\nSaved: {OUT_PATH}", flush=True)


if __name__ == "__main__":
    main()
