"""src/a2_train.py — Track A2 step 4: A1 + iterative noisy-student retrain.

Trains the four_track A2 branch by mixing the existing A1 focal-clip pipeline
with the OOF pseudo-labels from `data/processed/a2_pseudo_soft.npz`.
Sampling rule: per training step, with `--pseudo-ratio` probability draw a
random pseudo chunk; else draw the indexed train clip. Each fold's pseudo
pool is filtered to `oof_bucket == fold` so fold k never trains on a
pseudo-label generated by itself (Sydorskyi OOF safety, see new_plan.md
§14.17).

Differences vs `train_a1.py`:
  - Wraps `BirdTrainDatasetA1` in `MixedTrainPseudoDataset`
  - New args: `--pseudo-npz`, `--pseudo-ratio`
  - Saves checkpoints under `four_track/models/a2/` (a1 ckpts untouched)
  - Default loss = hybrid (matches v62 baseline; soft labels supported by
    BCE + ASL terms natively — see losses.py)

Recipe is iter-1 of the §14.17.5 Track-A2 plan: pseudo + train mixed
without cross-mixup; if iter-1 lifts LB we add cross-mixup in iter-2.

Note: an older `train_a2.py` exists in this repo for a different approach
(GT-anchor-only soundscape supervision via SoundscapeTrainDataset). This
file is the §14.17 noisy-student version and is intentionally a sibling
file, not a replacement.

Usage:
    # Single fold smoke (1 ep, 1 batch, 1 val batch)
    python -u src/a2_train.py --fold 0 --smoke-test

    # All five folds, 25 ep each, default 0.4 pseudo ratio
    python -u src/a2_train.py --folds 0,1,2,3,4 --loss hybrid

    # Skip pseudo for a controlled A1-baseline parity run
    python -u src/a2_train.py --folds 0,1,2,3,4 --pseudo-ratio 0.0
"""

import argparse
import gc
import random
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torchaudio.transforms as T
from sklearn.metrics import roc_auc_score
from torch.utils.data import DataLoader

# ── Path wiring ───────────────────────────────────────────────────────────────
HERE       = Path(__file__).resolve().parent
FT_ROOT    = HERE.parent
ROOT       = FT_ROOT.parent
PARENT_SRC = ROOT / "src"

if str(PARENT_SRC) not in sys.path:
    sys.path.insert(0, str(PARENT_SRC))
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import config  # noqa: E402
from config import (  # noqa: E402
    RAW, PROC,
    SAMPLE_RATE, CHUNK_SAMPLES, N_MELS,
    BATCH_SIZE, LR, LR_MIN, WEIGHT_DECAY, T_0,
    SPEC_TIME_MASK_PROB, SPEC_FREQ_MASK_PROB,
    get_species_index,
)
from utils import load_audio, pad_or_crop, waveform_to_mel  # noqa: E402

from dataset_a1 import BirdTrainDatasetA1  # noqa: E402
from dataset_a2 import SoundscapePseudoDataset, MixedTrainPseudoDataset  # noqa: E402
from losses import AsymmetricLossOptimized, HybridBceAsl  # noqa: E402
from model_a1 import BirdSEDModelA1  # noqa: E402

A2_MODELS_DIR = FT_ROOT / "models" / "a2"
DEFAULT_PSEUDO_NPZ = FT_ROOT / "data" / "processed" / "a2_pseudo_soft.npz"


# ── Validation: 66-file expert-labeled SS set (val_v2 substrate) ──────────────

def build_soundscape_val(sp2idx: dict) -> tuple:
    """Per-row mels + multi-hot labels from train_soundscapes_labels.csv.

    Identical to train_a1.build_soundscape_val. Same gate (val_v2 0.7414
    hybrid baseline applies); see new_plan.md §14.17.5 step 5 channel A.
    """
    df = pd.read_csv(RAW / "train_soundscapes_labels.csv")
    n_classes   = config.N_CLASSES
    soundsc_dir = RAW / "train_soundscapes"

    def _parse_time(s: str) -> int:
        h, m, sec = str(s).split(":")
        return int(h) * 3600 + int(m) * 60 + int(sec)

    val_mels   = []
    val_labels = np.zeros((len(df), n_classes), dtype=np.float32)

    for i, row in df.iterrows():
        t_start = _parse_time(row["start"])
        t_end   = _parse_time(row["end"])
        path    = soundsc_dir / str(row["filename"])
        try:
            wav     = load_audio(path)
            s, e    = int(t_start * SAMPLE_RATE), int(t_end * SAMPLE_RATE)
            segment = wav[s:e] if e <= len(wav) else wav[s:]
            segment = pad_or_crop(segment, CHUNK_SAMPLES, random_crop=False)
            mel     = waveform_to_mel(segment)
        except Exception as ex:
            print(f"  [warn] skipping {row['filename']} @ {t_start}s: {ex}", flush=True)
            mel = torch.zeros(3, N_MELS, 512)
        val_mels.append(mel)

        for sp in str(row["primary_label"]).split(";"):
            sp = sp.strip()
            if sp in sp2idx:
                val_labels[i, sp2idx[sp]] = 1.0

    return val_mels, val_labels


@torch.no_grad()
def validate(
    model: nn.Module,
    val_mels: list,
    val_labels: np.ndarray,
    device: torch.device,
    batch_size: int = 32,
    max_batches: int | None = None,
) -> float:
    model.eval()
    all_probs = []
    n_done = 0
    for i in range(0, len(val_mels), batch_size):
        batch = torch.stack(val_mels[i: i + batch_size]).to(device)
        with torch.amp.autocast(device_type="cuda", dtype=torch.bfloat16):
            out = model(batch)
        all_probs.append(torch.sigmoid(out["clip_logits"]).float().cpu().numpy())
        n_done += 1
        if max_batches is not None and n_done >= max_batches:
            break

    probs = np.concatenate(all_probs, axis=0)
    if probs.shape[0] < val_labels.shape[0]:
        val_labels = val_labels[: probs.shape[0]]
    present = val_labels.sum(axis=0) > 0
    if present.sum() == 0:
        return 0.0
    try:
        return float(roc_auc_score(
            val_labels[:, present], probs[:, present], average="macro"
        ))
    except ValueError:
        return 0.0


# ── Trainer ───────────────────────────────────────────────────────────────────

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def train_one_fold(
    fold: int,
    backbone: str,
    epochs: int,
    seed: int,
    loss_name: str,
    mixstyle_p: float,
    smoke_test: bool,
    pseudo_npz: Path,
    pseudo_ratio: float,
    cap_k: int,
    train_per_class: np.ndarray | None,
    val_cache: tuple | None = None,
    use_wandb: bool = False,
    wandb_project: str = "birdclef-2026",
    wandb_group: str | None = None,
    wandb_tags: list[str] | None = None,
    wandb_run_prefix: str = "a2",
    lr: float | None = None,
    weight_decay: float | None = None,
    warmup_epochs: int = 0,
    save_suffix: str = "",
) -> tuple:
    """Train a single Track-A2 fold and return (best_auc, save_path, val_cache)."""
    set_seed(seed + fold)

    device = torch.device("cuda")
    torch.backends.cuda.enable_flash_sdp(True)
    torch.backends.cuda.enable_mem_efficient_sdp(True)
    torch.backends.cudnn.benchmark = True

    # ── Train data (focal clips) ─────────────────────────────────────────────
    df       = pd.read_csv(PROC / "train_folds.csv")
    train_df = df[df["fold"] != fold].reset_index(drop=True)
    if smoke_test:
        train_df = train_df.head(BATCH_SIZE * 2)

    train_ds_focal = BirdTrainDatasetA1(train_df, augment=True)
    print(f"Fold {fold}: {len(train_ds_focal)} focal clips", flush=True)

    # ── Pseudo data (OOF soundscape, fold-filtered) ─────────────────────────
    if pseudo_ratio > 0:
        pseudo_ds = SoundscapePseudoDataset(
            pseudo_npz, fold_filter=fold, augment=True,
            cap_k=cap_k, train_per_class=train_per_class,
        )
        if smoke_test:
            # Truncate so smoke runs through quickly even if the pseudo
            # bucket has many thousands of entries.
            pseudo_ds.files   = pseudo_ds.files[:8]
            pseudo_ds.starts  = pseudo_ds.starts[:8]
            pseudo_ds.buckets = pseudo_ds.buckets[:8]
            pseudo_ds.soft    = pseudo_ds.soft[:8]
        print(f"Fold {fold}: pseudo subset (bucket=={fold}) → "
              f"{len(pseudo_ds)} chunks  ratio={pseudo_ratio:.2f}", flush=True)
        train_ds = MixedTrainPseudoDataset(train_ds_focal, pseudo_ds, pseudo_ratio)
    else:
        print(f"Fold {fold}: pseudo_ratio=0 → focal-only baseline parity run",
              flush=True)
        train_ds = train_ds_focal

    train_dl = DataLoader(
        train_ds,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=0 if smoke_test else config.NUM_WORKERS,
        pin_memory=True,
        drop_last=True,
        persistent_workers=not smoke_test,
        multiprocessing_context=None if smoke_test else "spawn",
    )
    print(f"Fold {fold}: {len(train_dl)} batches/epoch", flush=True)

    # ── Validation (val_v2: 66 GT-labeled SS files) ─────────────────────────
    sp2idx = get_species_index()
    if val_cache is None:
        print("Building soundscape validation set …", flush=True)
        val_mels, val_labels = build_soundscape_val(sp2idx)
        val_cache = (val_mels, val_labels)
    else:
        val_mels, val_labels = val_cache
    n_present = int((val_labels.sum(axis=0) > 0).sum())
    print(f"  {len(val_mels)} val segments, {n_present} species present", flush=True)

    # ── Model ────────────────────────────────────────────────────────────────
    freq_mask = T.FrequencyMasking(freq_mask_param=27).to(device)
    time_mask = T.TimeMasking(time_mask_param=64).to(device)

    model = BirdSEDModelA1(
        backbone_name=backbone,
        mixstyle_p=mixstyle_p,
    ).to(device)

    eff_lr = LR if lr is None else lr
    eff_wd = WEIGHT_DECAY if weight_decay is None else weight_decay
    optimizer = torch.optim.AdamW(model.parameters(), lr=eff_lr, weight_decay=eff_wd)
    if warmup_epochs > 0:
        warmup_sched = torch.optim.lr_scheduler.LinearLR(
            optimizer, start_factor=0.1, end_factor=1.0, total_iters=warmup_epochs
        )
        cosine_sched = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=max(epochs - warmup_epochs, 1), eta_min=LR_MIN
        )
        scheduler = torch.optim.lr_scheduler.SequentialLR(
            optimizer, schedulers=[warmup_sched, cosine_sched],
            milestones=[warmup_epochs],
        )
        print(f"  [recipe] lr={eff_lr}  wd={eff_wd}  warmup={warmup_epochs}ep  "
              f"cosine→{LR_MIN}  (no warm restarts)", flush=True)
    else:
        scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(
            optimizer, T_0=T_0, eta_min=LR_MIN
        )
        if lr is not None or weight_decay is not None:
            print(f"  [recipe] lr={eff_lr}  wd={eff_wd}  warm-restart T_0={T_0}",
                  flush=True)

    if loss_name == "asl":
        loss_fn = AsymmetricLossOptimized(reduction="none")
    elif loss_name == "hybrid":
        loss_fn = HybridBceAsl(bce_weight=0.5)
    elif loss_name == "bce":
        loss_fn = nn.BCEWithLogitsLoss(reduction="none")
    else:
        raise ValueError(f"Unsupported loss '{loss_name}' for Track A2")

    autocast_ctx = torch.amp.autocast(device_type="cuda", dtype=torch.bfloat16)

    A2_MODELS_DIR.mkdir(parents=True, exist_ok=True)
    suffix = ("_smoke" if smoke_test else "") + save_suffix
    save_path = A2_MODELS_DIR / f"a2_{backbone}_fold{fold}_seed{seed}_{loss_name}{suffix}.pt"

    # ── Optional W&B run init (opt-in via --use-wandb) ───────────────────────
    wandb_run = None
    if use_wandb:
        import wandb  # imported lazily so non-wandb runs have no dependency
        wandb_run = wandb.init(
            project=wandb_project,
            group=wandb_group,
            name=f"{wandb_run_prefix}-fold{fold}",
            tags=wandb_tags or [],
            config={
                "backbone": backbone,
                "fold": fold,
                "epochs": epochs,
                "seed": seed,
                "loss": loss_name,
                "mixstyle_p": mixstyle_p,
                "pseudo_npz": str(pseudo_npz),
                "pseudo_ratio": pseudo_ratio,
                "cap_k": cap_k,
                "save_dir": str(A2_MODELS_DIR),
                "save_path": str(save_path),
                "n_focal": len(train_ds_focal),
                "n_pseudo": len(pseudo_ds) if pseudo_ratio > 0 else 0,
                "batch_size": BATCH_SIZE,
                "lr": LR,
                "weight_decay": WEIGHT_DECAY,
                "t_0": T_0,
                "lr_min": LR_MIN,
            },
            reinit="finish_previous",
        )

    # ── Training loop ────────────────────────────────────────────────────────
    best_auc = 0.0
    for epoch in range(1, epochs + 1):
        epoch_start = time.time()
        model.train()
        running_loss = 0.0
        n_seen = 0

        for batch_idx, (mels, labels, sec_mask) in enumerate(train_dl):
            mels     = mels.to(device, non_blocking=True)
            labels   = labels.to(device, non_blocking=True)
            sec_mask = sec_mask.to(device, non_blocking=True)

            if random.random() < SPEC_FREQ_MASK_PROB:
                mels = freq_mask(mels)
            if random.random() < SPEC_TIME_MASK_PROB:
                mels = time_mask(mels)

            optimizer.zero_grad()
            with autocast_ctx:
                out      = model(mels)
                loss_per = loss_fn(out["clip_logits"], labels)
                loss     = (loss_per * sec_mask).mean()

            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()

            running_loss += loss.item()
            n_seen       += 1

            if smoke_test and batch_idx >= 0:
                break

        scheduler.step()

        avg_loss = running_loss / max(n_seen, 1)
        val_auc  = validate(
            model, val_mels, val_labels, device,
            max_batches=1 if smoke_test else None,
        )

        elapsed = int(time.time() - epoch_start)
        mins, s = divmod(elapsed, 60)

        best_marker = ""
        if val_auc > best_auc:
            best_auc = val_auc
            torch.save(model.state_dict(), save_path)
            best_marker = " ★ BEST"

        print("=" * 40, flush=True)
        print(
            f"Fold {fold}  Epoch {epoch:2d}/{epochs}: "
            f"train_loss={avg_loss:.4f}  "
            f"val_roc_auc={val_auc:.4f}  "
            f"time={mins}m {s:02d}s  "
            f"{time.strftime('%Y-%m-%d %H:%M:%S')}"
            f"{best_marker}",
            flush=True,
        )
        print("=" * 40, flush=True)

        if wandb_run is not None:
            wandb_run.log({
                "epoch": epoch,
                "train_loss": avg_loss,
                "val_roc_auc": val_auc,
                "best_val_roc_auc": best_auc,
                "epoch_seconds": elapsed,
                "lr": optimizer.param_groups[0]["lr"],
            })

        # GB10 unified-memory hygiene — see four_track/CLAUDE.md
        gc.collect()
        torch.cuda.empty_cache()

    print(f"\nFold {fold} complete. Best val ROC-AUC: {best_auc:.4f}", flush=True)
    print(f"Checkpoint → {save_path}\n", flush=True)

    if wandb_run is not None:
        wandb_run.summary["final_best_val_roc_auc"] = best_auc
        wandb_run.finish()

    return best_auc, save_path, val_cache


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    p = argparse.ArgumentParser(description="Track A2 — A1 + iterative noisy-student pseudos")
    p.add_argument("--fold",         type=int, default=None)
    p.add_argument("--folds",        type=str, default=None,
                   help="Comma-separated list, e.g. 0,1,2,3,4")
    p.add_argument("--backbone",     type=str, default=config.BACKBONE)
    p.add_argument("--epochs",       type=int, default=25)
    p.add_argument("--seed",         type=int, default=config.SEED)
    p.add_argument("--loss",         type=str, default="hybrid",
                   choices=["bce", "asl", "hybrid"])
    p.add_argument("--mixstyle-p",   type=float, default=0.5)
    p.add_argument("--smoke-test",   action="store_true")
    p.add_argument("--pseudo-npz",   type=Path, default=DEFAULT_PSEUDO_NPZ,
                   help=f"Path to filtered pseudo NPZ (default {DEFAULT_PSEUDO_NPZ})")
    p.add_argument("--pseudo-ratio", type=float, default=0.4,
                   help="Per-step probability of drawing a pseudo chunk "
                        "(default 0.4 per Sydorskyi)")
    p.add_argument("--cap-k", type=int, default=0,
                   help="Per-class pseudo cap: keep at most cap_k * train_count "
                        "rows per top-1 species. 0 disables (legacy iter-1). "
                        "Iter-1.5 default is 10 — see new_plan.md §14.17.10.7.")
    p.add_argument("--use-wandb", action="store_true",
                   help="Log per-epoch metrics to Weights & Biases. Off by "
                        "default; requires `wandb login` on the executing host.")
    p.add_argument("--wandb-project", type=str, default="birdclef-2026")
    p.add_argument("--wandb-group", type=str, default=None,
                   help="Group name (defaults to a2-YYYYMMDD-HHMMSS). All folds "
                        "in this run share the same group so they plot together.")
    p.add_argument("--wandb-tag", action="append", default=[],
                   help="Repeatable. E.g. --wandb-tag a3 --wandb-tag topk5")
    p.add_argument("--wandb-run-prefix", type=str, default="a2",
                   help="Run name prefix; per-fold runs land as `<prefix>-foldN`.")
    p.add_argument("--lr", type=float, default=None,
                   help="Override learning rate. Default: config.LR (5e-4). "
                        "Use 1e-4 for transformer-style backbones.")
    p.add_argument("--weight-decay", type=float, default=None,
                   help="Override weight decay. Default: config.WEIGHT_DECAY "
                        "(1e-4). Use 5e-2 for transformer-style backbones.")
    p.add_argument("--warmup-epochs", type=int, default=0,
                   help="If >0, swap warm-restart cosine for LinearLR warmup → "
                        "single-cycle CosineAnnealingLR (no restarts). 2 is "
                        "the standard transformer-recipe choice.")
    p.add_argument("--save-suffix", type=str, default="",
                   help="Appended to ckpt filename so recipe variants don't "
                        "clobber the canonical fold ckpt.")
    args = p.parse_args()

    if args.smoke_test:
        folds  = [args.fold if args.fold is not None else 0]
        epochs = max(1, min(args.epochs, 5))
    else:
        if args.fold is not None and args.folds is not None:
            sys.exit("--fold and --folds are mutually exclusive")
        if args.folds is not None:
            folds = [int(x) for x in args.folds.split(",")]
        elif args.fold is not None:
            folds = [args.fold]
        else:
            folds = [0, 1, 2, 3, 4]
        epochs = args.epochs

    print("=" * 60, flush=True)
    print("Track A2 — A1 + iterative noisy-student pseudos", flush=True)
    print(f"  backbone     : {args.backbone}", flush=True)
    print(f"  folds        : {folds}", flush=True)
    print(f"  epochs       : {epochs}", flush=True)
    print(f"  loss         : {args.loss}", flush=True)
    print(f"  mixstyle_p   : {args.mixstyle_p}", flush=True)
    print(f"  pseudo_npz   : {args.pseudo_npz}", flush=True)
    print(f"  pseudo_ratio : {args.pseudo_ratio}", flush=True)
    print(f"  cap_k        : {args.cap_k}", flush=True)
    print(f"  smoke_test   : {args.smoke_test}", flush=True)
    print(f"  lr           : {args.lr if args.lr is not None else f'config.LR ({LR})'}", flush=True)
    print(f"  weight_decay : {args.weight_decay if args.weight_decay is not None else f'config.WEIGHT_DECAY ({WEIGHT_DECAY})'}", flush=True)
    print(f"  warmup_epochs: {args.warmup_epochs}", flush=True)
    print(f"  save_suffix  : '{args.save_suffix}'", flush=True)
    print(f"  models →     : {A2_MODELS_DIR}", flush=True)
    print("=" * 60, flush=True)

    if args.pseudo_ratio > 0 and not args.pseudo_npz.exists():
        sys.exit(f"Pseudo NPZ missing: {args.pseudo_npz}\n"
                 f"Run a2_emit_oof_pseudo.py + a2_filter_pseudo.py first, "
                 f"or pass --pseudo-ratio 0 for a baseline parity run.")

    # Per-class focal-clip counts (global, all folds) for the cap rule.
    train_per_class = None
    if args.cap_k > 0:
        train_full = pd.read_csv(PROC / "train_folds.csv")
        sp2idx = get_species_index()
        train_per_class = np.zeros(config.N_CLASSES, dtype=np.int64)
        for sp, n in train_full["primary_label"].astype(str).value_counts().items():
            if sp in sp2idx:
                train_per_class[sp2idx[sp]] = int(n)

    wandb_group = args.wandb_group or (
        f"{args.wandb_run_prefix}-{time.strftime('%Y%m%d-%H%M%S')}"
        if args.use_wandb else None
    )

    val_cache = None
    fold_results = []
    t0 = time.time()
    for f in folds:
        best_auc, save_path, val_cache = train_one_fold(
            fold=f,
            backbone=args.backbone,
            epochs=epochs,
            seed=args.seed,
            loss_name=args.loss,
            mixstyle_p=args.mixstyle_p,
            smoke_test=args.smoke_test,
            pseudo_npz=args.pseudo_npz,
            pseudo_ratio=args.pseudo_ratio,
            cap_k=args.cap_k,
            train_per_class=train_per_class,
            val_cache=val_cache,
            use_wandb=args.use_wandb,
            wandb_project=args.wandb_project,
            wandb_group=wandb_group,
            wandb_tags=args.wandb_tag,
            wandb_run_prefix=args.wandb_run_prefix,
            lr=args.lr,
            weight_decay=args.weight_decay,
            warmup_epochs=args.warmup_epochs,
            save_suffix=args.save_suffix,
        )
        fold_results.append((f, best_auc, save_path))
        gc.collect()
        torch.cuda.empty_cache()

    elapsed = int(time.time() - t0)
    h, rem = divmod(elapsed, 3600)
    m, s   = divmod(rem, 60)
    print("=" * 60, flush=True)
    print(f"Track A2 run complete  total time: {h}h {m:02d}m {s:02d}s", flush=True)
    for f, auc, path in fold_results:
        print(f"  fold {f}: best val_roc_auc = {auc:.4f}  → {path.name}", flush=True)
    if len(fold_results) > 1:
        mean_auc = float(np.mean([a for _, a, _ in fold_results]))
        print(f"  mean fold val_roc_auc = {mean_auc:.4f}", flush=True)
    print("=" * 60, flush=True)


if __name__ == "__main__":
    main()
