#!/bin/bash
# PCEN Stage 1 — focal-only training (Step 1 of #15h)
#
# PURPOSE: Train a PCEN-native baseline from scratch using ONLY focal (labeled)
#          data. No pseudo-labels. This produces a checkpoint whose internal
#          representations match PCEN feature space, enabling correct pseudo-label
#          generation in Step 2.
#
# WHY FOCAL-ONLY:
#   v8/v9 trained from scratch with PCEN but used pseudo_labels_v4.csv,
#   which was generated by a log-mel model → calibration mismatch → bell-curve
#   decline after epoch 7-14. This run avoids pseudo-labels entirely.
#
# GATE:
#   val_roc_auc ≥ 0.73 → PCEN Stage 1 is working. Proceed to Step 2 (generate
#                         PCEN pseudo-labels from this checkpoint).
#   val_roc_auc < 0.70 → Something is wrong. Debug PCEN or training params.
#
# NOTE: v8 (PCEN+pseudo, 20ep) peaked 0.7214; v9 (PCEN+pseudo, 40ep) peaked
#       0.7308. Without pseudo-label noise and trained focal-only, this should
#       be cleaner even if slightly lower peak (fewer training samples).
#
# Usage:
#   conda activate kaggle
#   cd /home/swatson/work/MachineLearning/kaggle/BirdCLEF
#   rm -f log/train_*.log
#   nohup bash scripts/pcen_stage1_fold0.sh \
#     > log/pcen_stage1_$(date +%Y%m%d_%H%M%S).log 2>&1 &
#   tail -f log/pcen_stage1_*.log

set -e

ROOT=/home/swatson/work/MachineLearning/kaggle/BirdCLEF
PYTHON=/home/swatson/miniconda3/envs/kaggle/bin/python
KAGGLE=/home/swatson/miniconda3/envs/kaggle/bin/kaggle

BACKBONE="tf_efficientnet_b0.ns_jft_in1k"
VERSION=13         # v13 = PCEN Stage 1 focal-only (no pseudo, from scratch)
EPOCHS=20
SEED=42

DATASET_SLUG="stevewatson999/birdclef2026-sed-models"

cd "$ROOT"

echo "============================================================"
echo "BirdCLEF+ 2026 — PCEN Stage 1 (focal-only, #15h step 1)"
echo "Backbone      : $BACKBONE  (v$VERSION)"
echo "Epochs        : $EPOCHS   Seed: $SEED"
echo "Pseudo CSV    : NONE (focal data only)"
echo "Spectrogram   : PCEN (utils.py default)"
echo "Loss          : BCE"
echo "Training      : FROM SCRATCH (random init)"
echo "LR schedule   : CosineAnnealingWarmRestarts (T_0=5)"
echo "Started       : $(date)"
echo "============================================================"

"$PYTHON" -u "$ROOT/src/train.py" \
    --fold      0 \
    --backbone  "$BACKBONE" \
    --epochs    "$EPOCHS" \
    --seed      "$SEED" \
    --version   "$VERSION"

echo ""
echo "============================================================"
echo "PCEN Stage 1 (focal-only) training complete: $(date)"
echo ""
echo "Checkpoint saved:"
ls -lh "$ROOT/models/sed_${BACKBONE}_fold0_seed${SEED}_v${VERSION}.pt" 2>/dev/null || echo "  (not found)"
echo "============================================================"

# ── Push models to Kaggle dataset ─────────────────────────────────────────────
# Use a temp directory with only the needed checkpoint(s) + metadata
# to avoid uploading the entire models/ directory.
TMP_DS="$(mktemp -d)"
cp "$ROOT/models/dataset-metadata.json" "$TMP_DS/"
cp "$ROOT/models/sed_${BACKBONE}_fold0_seed${SEED}_v${VERSION}.pt" "$TMP_DS/"
echo ""
echo "Pushing models to Kaggle dataset: $DATASET_SLUG"
echo "  Files:"
ls -lh "$TMP_DS/"
"$KAGGLE" datasets version \
    -p "$TMP_DS" \
    -m "PCEN Stage 1 focal-only: EffB0-v${VERSION} fold-0 (${EPOCHS}ep, PCEN, BCE, from scratch)" \
    --dir-mode zip
rm -rf "$TMP_DS"

echo ""
echo "Waiting 30s for dataset version to propagate before pushing notebook..."
sleep 30

# ── Push inference notebook ───────────────────────────────────────────────────
echo ""
echo "Pushing inference notebook: stevewatson999/birdclef-2026-sed-inference"
"$KAGGLE" kernels push -p "$ROOT/jupyter/sed"

echo ""
echo "============================================================"
echo "PCEN Stage 1 pipeline complete: $(date)"
echo ""
echo "NEXT STEPS:"
echo "  1. Wait for notebook to finish running on Kaggle (~30 min)"
echo "  2. Submit output to competition — tag: PCEN_Stage1_v${VERSION}"
echo "  3. Record LB score in plan.md"
echo "  4. If val_roc_auc >= 0.73 → Generate PCEN pseudo-labels (Step 2)"
echo "     python -u src/pseudo_label.py --ckpt models/sed_${BACKBONE}_fold0_seed${SEED}_v${VERSION}.pt"
echo "  5. Then PCEN self-train with PCEN pseudo-labels (Step 3)"
echo "============================================================"
