#!/bin/bash
# PCEN Self-Train — Step 3 of #15h
#
# PURPOSE: Self-train an EffB0 with PCEN + BCE using PCEN-native pseudo-labels
#          (generated by the PCEN Stage 1 v13 checkpoint in Step 2).
#          Warm-starts from v13. This is the critical test: do PCEN-native
#          pseudo-labels break the bell-curve decline seen in v8/v9?
#
# KEY DIFFERENCES FROM v8/v9:
#   - Pseudo-labels generated by a PCEN-native model (v13), not a log-mel model
#   - Warm-start from v13 (PCEN-trained), not from log-mel v4
#   - BCE loss (not ASL — validated in v10/v11/v12 that ASL fails with warm-start)
#   - Single cosine decay LR (not warm_restarts — from-scratch+PCEN needs smooth decay)
#   - No Freq-MixStyle, no dual-loss (minimal recipe, PCEN validation only)
#
# GATE:
#   val_roc_auc ≥ 0.76 → PCEN self-train working. Proceed to 5-fold.
#   val_roc_auc < 0.73 → PCEN pseudo-labels not helping. Investigate.
#
# Usage:
#   conda activate kaggle
#   cd /home/swatson/work/MachineLearning/kaggle/BirdCLEF
#   rm -f log/train_*.log
#   nohup bash scripts/pcen_self_train_fold0.sh \
#     > log/pcen_self_train_$(date +%Y%m%d_%H%M%S).log 2>&1 &
#   tail -f log/pcen_self_train_*.log

set -e

ROOT=/home/swatson/work/MachineLearning/kaggle/BirdCLEF
PYTHON=/home/swatson/miniconda3/envs/kaggle/bin/python
KAGGLE=/home/swatson/miniconda3/envs/kaggle/bin/kaggle

BACKBONE="tf_efficientnet_b0.ns_jft_in1k"
VERSION=14         # v14 = PCEN self-train with PCEN pseudo-labels (#15h step 3)
EPOCHS=30
SEED=42
PSEUDO_CSV="$ROOT/data/processed/pseudo_labels_pcen_v1.csv"
INIT_CKPT="$ROOT/models/sed_${BACKBONE}_fold0_seed${SEED}_v13.pt"

DATASET_SLUG="stevewatson999/birdclef2026-sed-models"

cd "$ROOT"

# Verify pseudo-labels and init checkpoint exist
if [ ! -f "$PSEUDO_CSV" ]; then
    echo "ERROR: Pseudo-label CSV not found: $PSEUDO_CSV"
    echo "  Run Step 2 first: python -u src/pseudo_label.py --folds '0' --ckpt-version 13 --version 5 --output $PSEUDO_CSV"
    exit 1
fi
if [ ! -f "$INIT_CKPT" ]; then
    echo "ERROR: Init checkpoint not found: $INIT_CKPT"
    echo "  Run Step 1 first: bash scripts/pcen_stage1_fold0.sh"
    exit 1
fi

echo "============================================================"
echo "BirdCLEF+ 2026 — PCEN Self-Train (#15h Step 3)"
echo "Backbone      : $BACKBONE  (v$VERSION)"
echo "Epochs        : $EPOCHS   Seed: $SEED"
echo "Pseudo CSV    : $PSEUDO_CSV"
echo "Init checkpoint: $INIT_CKPT"
echo "Spectrogram   : PCEN (utils.py default)"
echo "Loss          : BCE (--use-bce)"
echo "LR schedule   : cosine (single decay)"
echo "Freq-MixStyle : OFF (minimal recipe)"
echo "Dual loss     : OFF (clip-level only)"
echo "Model soup    : OFF (fold-0 diagnostic, not needed)"
echo "Started       : $(date)"
echo "============================================================"

"$PYTHON" -u "$ROOT/src/self_train.py" \
    --fold      0 \
    --backbone  "$BACKBONE" \
    --epochs    "$EPOCHS" \
    --seed      "$SEED" \
    --pseudo-csv "$PSEUDO_CSV" \
    --pseudo-power 1.5 \
    --init-ckpt "$INIT_CKPT" \
    --version   "$VERSION" \
    --use-bce \
    --no-freq-mixstyle \
    --no-dual-loss \
    --lr-schedule cosine \
    --soup-start-ep 0

echo ""
echo "============================================================"
echo "PCEN Self-Train complete: $(date)"
echo ""
echo "Checkpoint saved:"
ls -lh "$ROOT/models/sed_${BACKBONE}_fold0_seed${SEED}_v${VERSION}.pt" 2>/dev/null || echo "  (not found)"
echo "============================================================"

# ── Push models to Kaggle dataset ─────────────────────────────────────────────
TMP_DS="$(mktemp -d)"
cp "$ROOT/models/dataset-metadata.json" "$TMP_DS/"
cp "$ROOT/models/sed_${BACKBONE}_fold0_seed${SEED}_v${VERSION}.pt" "$TMP_DS/"
echo ""
echo "Pushing models to Kaggle dataset: $DATASET_SLUG"
echo "  Files:"
ls -lh "$TMP_DS/"
"$KAGGLE" datasets version \
    -p "$TMP_DS" \
    -m "PCEN self-train: EffB0-v${VERSION} fold-0 (${EPOCHS}ep, PCEN, BCE, warm-start v13, PCEN pseudo-labels)" \
    --dir-mode zip
rm -rf "$TMP_DS"

echo ""
echo "Waiting 30s for dataset version to propagate before pushing notebook..."
sleep 30

# ── Push inference notebook ───────────────────────────────────────────────────
echo ""
echo "Pushing inference notebook: stevewatson999/birdclef-2026-sed-inference"
"$KAGGLE" kernels push -p "$ROOT/jupyter/sed"

echo ""
echo "============================================================"
echo "PCEN Self-Train pipeline complete: $(date)"
echo ""
echo "NEXT STEPS:"
echo "  1. Wait for notebook to finish running on Kaggle (~30 min)"
echo "  2. Submit output to competition — tag: PCEN_SelfTrain_v${VERSION}"
echo "  3. Record LB score in plan.md"
echo "  4. If val_roc_auc >= 0.76 → Run 5-fold PCEN self-train"
echo "============================================================"
